<script lang="ts">
	import PageHeader from '$lib/components/ui/PageHeader.svelte'
	import Banner from '$lib/components/ui/Banner.svelte'
	import EmptyState from '$lib/components/ui/EmptyState.svelte'
	import Container from '$lib/components/ui/Container.svelte'
	import { formatShortDate } from '$lib/utils/format'
	import type { PageData } from './$types'
	import Badge from '$lib/components/ui/Badge.svelte'

	let { data }: { data: PageData } = $props()
</script>

<svelte:head>
	<title>Performance — Veent HRIS</title>
</svelte:head>

<div
	class={data.isAdmin
		? 'space-y-6'
		: 'flex min-h-[calc(100dvh-6rem)] flex-col gap-6 lg:h-[calc(100dvh-4rem)] lg:min-h-0'}
>
	<PageHeader title="Performance" />

	<!-- #178 readiness note. Informational, never a gate: it disables nothing and blocks no
	     action. The count is 0 for anyone without ADMINISTER_HR_ORGWIDE (see the load), so the
	     capability check is the server's and `> 0` is the whole client-side condition. -->
	{#if data.templateBackfill > 0}
		<Banner kind="warning">
			{data.templateBackfill} active
			{data.templateBackfill === 1 ? 'employee has' : 'employees have'} no assigned template. This is
			a readiness note, not a blocker.
		</Banner>
	{/if}

	<!-- Review Cycles (HR) — read-only. #178: cycles are generated by the nightly cron, so there
	     is no create form and no hand-run status transition; this is the record of what it made. -->
	{#if data.isAdmin && data.cycles.length}
		<Container tone="card" flush>
			{#snippet toolbar()}
				<h2 class="text-lg font-semibold">Review Cycles</h2>
			{/snippet}
			<div class="card-scroll overflow-x-auto">
				<table class="w-full text-sm">
					<thead class="border-b bg-muted/50">
						<tr>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Period</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
						</tr>
					</thead>
					<tbody class="divide-y">
						{#each data.cycles as c (c.id)}
							<tr class="hover:bg-muted/30">
								<td class="px-4 py-3 font-medium">{c.name}</td>
								<td class="px-4 py-3 text-muted-foreground"
									>{formatShortDate(c.startDate)} – {formatShortDate(c.endDate)}</td
								>
								<td class="px-4 py-3"><Badge status={c.status} domain="reviewCycle" /></td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</Container>
	{/if}

	<!-- Stalled Sign-offs (HR) — #178 item 145 / SPEC AC12. A DIFFERENT LIST from the
	     unreviewable one on purpose: unreviewable means the review was never created; stalled
	     means it exists, is part-way signed, and its next signatory resolves to nobody. They need
	     different fixes, so they must not be merged into one section.

	     `canHrOrgwide` comes from the load, which is where the capability is really checked. The
	     flag exists so this section is never rendered for someone who would only get a 403 — and
	     so an empty list still shows HR the good, all-clear state. -->
	{#if data.canHrOrgwide}
		<Container tone="card" flush empty={data.stalledSignoffs.length === 0}>
			{#snippet toolbar()}
				<h2 class="text-lg font-semibold">Stalled Sign-offs</h2>
				<a href="/departments" class="text-sm font-medium text-primary hover:underline"
					>Assign department heads</a
				>
			{/snippet}
			<p class="border-b px-4 py-3 text-sm text-muted-foreground">
				Reviews that are already under way but cannot move: the next person to sign is not assigned.
				This is not the same as a review that was never created.
			</p>
			<div class="card-scroll overflow-x-auto">
				<table class="w-full text-sm">
					<thead class="border-b bg-muted/50">
						<tr>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Employee</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Department</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Waiting on</th>
						</tr>
					</thead>
					<tbody class="divide-y">
						{#each data.stalledSignoffs as s (s.reviewId)}
							<tr class="hover:bg-muted/30">
								<td class="px-4 py-3"
									><a
										href="/performance/reviews/{s.reviewId}"
										class="font-medium text-primary hover:underline">{s.employeeName}</a
									></td
								>
								<td class="px-4 py-3 text-muted-foreground">{s.departmentName}</td>
								<td class="px-4 py-3 text-muted-foreground">{s.cycleName}</td>
								<td class="px-4 py-3">{s.slot.label} — no one is assigned</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>

			{#snippet emptyState()}
				<EmptyState
					title="No sign-off is stalled"
					description="Every review under way has someone who can sign it next."
				/>
			{/snippet}
		</Container>
	{/if}

	{#if data.isAdmin}
		<!-- My Reviews -->
		<Container tone="card" flush empty={data.myReviews.length === 0}>
			{#snippet toolbar()}
				<h2 class="text-lg font-semibold">My Reviews</h2>
			{/snippet}
			<div class="card-scroll overflow-x-auto">
				<table class="w-full text-sm">
					<thead class="border-b bg-muted/50">
						<tr>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Reviewer</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
						</tr>
					</thead>
					<tbody class="divide-y">
						{#each data.myReviews as review (review.id)}
							<tr class="hover:bg-muted/30">
								<td class="px-4 py-3"
									><a
										href="/performance/reviews/{review.id}"
										class="font-medium text-primary hover:underline">{review.cycle.name}</a
									></td
								>
								<td class="px-4 py-3 text-muted-foreground">
									{review.reviewer.lastName}, {review.reviewer.firstName}
								</td>
								<td class="px-4 py-3">
									<Badge status={review.status} domain="review" />
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>

			{#snippet emptyState()}
				<EmptyState title="No reviews" />
			{/snippet}
		</Container>

		<!-- Reviews to Complete (reviewer) -->
		{#if data.reviewsToGive.length}
			<Container tone="card" flush>
				{#snippet toolbar()}
					<h2 class="text-lg font-semibold">Reviews to Complete</h2>
				{/snippet}
				<div class="card-scroll overflow-x-auto">
					<table class="w-full text-sm">
						<thead class="border-b bg-muted/50">
							<tr>
								<th class="px-4 py-3 text-left font-medium text-muted-foreground">Employee</th>
								<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
								<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
							</tr>
						</thead>
						<tbody class="divide-y">
							{#each data.reviewsToGive as review (review.id)}
								<tr class="hover:bg-muted/30">
									<td class="px-4 py-3"
										><a
											href="/performance/reviews/{review.id}"
											class="font-medium text-primary hover:underline"
											>{review.employee.lastName}, {review.employee.firstName}</a
										></td
									>
									<td class="px-4 py-3 text-muted-foreground">{review.cycle.name}</td>
									<td class="px-4 py-3">
										<Badge status={review.status} domain="review" />
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</Container>
		{/if}
	{:else}
		<!-- My Reviews -->
		<section
			class={data.reviewsToGive.length
				? 'flex shrink-0 flex-col gap-3'
				: 'flex min-h-0 flex-1 flex-col gap-3'}
		>
			<h2 class="text-lg font-semibold">My Reviews</h2>
			<Container
				tone="card"
				flush
				class={data.reviewsToGive.length ? 'flex-none' : undefined}
				empty={data.myReviews.length === 0}
			>
				<div class="phone-scroll overflow-x-auto">
					<table class="w-full text-sm">
						<thead
							class="sticky top-0 z-10 border-b bg-card bg-[image:linear-gradient(hsl(var(--muted)/0.5),hsl(var(--muted)/0.5))]"
						>
							<tr>
								<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
								<th class="px-4 py-3 text-left font-medium text-muted-foreground">Reviewer</th>
								<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
							</tr>
						</thead>
						<tbody class="divide-y">
							{#each data.myReviews as review (review.id)}
								<tr class="hover:bg-muted/30">
									<td class="px-4 py-3"
										><a
											href="/performance/reviews/{review.id}"
											class="font-medium text-primary hover:underline">{review.cycle.name}</a
										></td
									>
									<td class="px-4 py-3 text-muted-foreground">
										{review.reviewer.lastName}, {review.reviewer.firstName}
									</td>
									<td class="px-4 py-3">
										<Badge status={review.status} domain="review" />
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>

				{#snippet emptyState()}
					<EmptyState title="No reviews" />
				{/snippet}
			</Container>
		</section>

		<!-- Reviews to Complete (reviewer) -->
		{#if data.reviewsToGive.length}
			<section class="flex min-h-0 flex-1 flex-col gap-3">
				<h2 class="text-lg font-semibold">Reviews to Complete</h2>
				<Container tone="card" flush>
					<div class="phone-scroll overflow-x-auto">
						<table class="w-full text-sm">
							<thead
								class="sticky top-0 z-10 border-b bg-card bg-[image:linear-gradient(hsl(var(--muted)/0.5),hsl(var(--muted)/0.5))]"
							>
								<tr>
									<th class="px-4 py-3 text-left font-medium text-muted-foreground">Employee</th>
									<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
									<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
								</tr>
							</thead>
							<tbody class="divide-y">
								{#each data.reviewsToGive as review (review.id)}
									<tr class="hover:bg-muted/30">
										<td class="px-4 py-3"
											><a
												href="/performance/reviews/{review.id}"
												class="font-medium text-primary hover:underline"
												>{review.employee.lastName}, {review.employee.firstName}</a
											></td
										>
										<td class="px-4 py-3 text-muted-foreground">{review.cycle.name}</td>
										<td class="px-4 py-3">
											<Badge status={review.status} domain="review" />
										</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				</Container>
			</section>
		{/if}
	{/if}
</div>
