import { createHash, createHmac } from 'node:crypto'

// AWS Signature Version 4 for the three operations the backup destination needs
// (PUT object, LIST bucket, DELETE object). ~100 lines of HMAC-SHA256 instead of
// @aws-sdk/client-s3, which pulls ~15MB plus a transitive tree into an image whose
// Dockerfile is explicitly size-optimised. `fetch` is built into Node, so there is no HTTP
// client dependency either (AD-005).
//
// The condition that decision rests on: because no S3-compatible environment exists to
// test against, this signer is pinned to AWS's OWN published test vectors in
// tests/unit/backup-s3-sigv4.test.ts. An expectation generated by this code and pasted
// back into the test would prove only that it is deterministic.

const ALGORITHM = 'AWS4-HMAC-SHA256'

export interface SigV4Request {
	method: string
	/** Absolute URI path, NOT yet percent-encoded. */
	path: string
	query: Record<string, string>
	headers: Record<string, string>
	/** Hex sha256 of the body. Never the literal UNSIGNED-PAYLOAD (S9). */
	payloadHash: string
}

export interface SigV4Credentials {
	accessKeyId: string
	secretAccessKey: string
	region: string
	service: string
}

export function sha256Hex(data: string | Buffer): string {
	return createHash('sha256').update(data).digest('hex')
}

// RFC 3986. encodeURIComponent leaves !'()* alone and AWS wants them encoded; the
// unreserved set -._~ must NOT be encoded (the get-unreserved vector checks exactly this).
function uriEncode(value: string): string {
	return encodeURIComponent(value).replace(
		/[!'()*]/g,
		(c) => '%' + c.charCodeAt(0).toString(16).toUpperCase()
	)
}

// Each path SEGMENT is encoded; the separators are not.
function canonicalUri(path: string): string {
	return path.split('/').map(uriEncode).join('/')
}

/** Total deadline per S3 call. A backup is not latency-sensitive; a stuck socket is the risk. */
const S3_REQUEST_TIMEOUT_MS = 60_000

function canonicalQuery(query: Record<string, string>): string {
	return Object.keys(query)
		.sort()
		.map((k) => `${uriEncode(k)}=${uriEncode(query[k])}`)
		.join('&')
}

// Header names lowercased, values trimmed with runs of internal whitespace collapsed,
// sorted by name.
function canonicalHeaderEntries(headers: Record<string, string>): [string, string][] {
	return Object.entries(headers)
		.map(([k, v]) => [k.toLowerCase(), String(v).trim().replace(/\s+/g, ' ')] as [string, string])
		.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0))
}

export function canonicalRequest(req: SigV4Request): string {
	const entries = canonicalHeaderEntries(req.headers)
	return [
		req.method,
		canonicalUri(req.path),
		canonicalQuery(req.query),
		entries.map(([k, v]) => `${k}:${v}`).join('\n') + '\n',
		entries.map(([k]) => k).join(';'),
		req.payloadHash
	].join('\n')
}

export function stringToSign(canonical: string, amzDate: string, scope: string): string {
	return [ALGORITHM, amzDate, scope, sha256Hex(canonical)].join('\n')
}

/** `20150830T123600Z` — basic-format ISO 8601, which is what SigV4 requires. */
export function amzDateOf(now: Date): string {
	return now
		.toISOString()
		.replace(/[-:]/g, '')
		.replace(/\.\d{3}/, '')
}

function hmac(key: Buffer | string, data: string): Buffer {
	return createHmac('sha256', key).update(data).digest()
}

/**
 * Sign a request. Returns the headers to SEND: the caller's own headers, plus `x-amz-date`
 * (supplied here so a caller cannot forget it) and `authorization`.
 */
export function signV4(
	req: SigV4Request,
	creds: SigV4Credentials,
	now: Date
): Record<string, string> {
	const amzDate = amzDateOf(now)
	const dateStamp = amzDate.slice(0, 8)
	const scope = `${dateStamp}/${creds.region}/${creds.service}/aws4_request`

	// Lowercase every incoming name FIRST. Spreading raw headers would let 'X-Amz-Date' and
	// 'x-amz-date' both survive, and the signed-header list would then carry x-amz-date
	// twice — a signature no endpoint will accept.
	const headers: Record<string, string> = {}
	for (const [k, v] of Object.entries(req.headers)) headers[k.toLowerCase()] = v
	headers['x-amz-date'] = amzDate
	const canonical = canonicalRequest({ ...req, headers })
	const signedHeaders = canonicalHeaderEntries(headers)
		.map(([k]) => k)
		.join(';')

	const kDate = hmac(`AWS4${creds.secretAccessKey}`, dateStamp)
	const kRegion = hmac(kDate, creds.region)
	const kService = hmac(kRegion, creds.service)
	const kSigning = hmac(kService, 'aws4_request')
	const signature = createHmac('sha256', kSigning)
		.update(stringToSign(canonical, amzDate, scope))
		.digest('hex')

	return {
		...headers,
		authorization: `${ALGORITHM} Credential=${creds.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`
	}
}

export interface S3Target {
	endpoint: string
	region: string
	bucket: string
	accessKeyId: string
	secretAccessKey: string
}

export interface S3Response {
	status: number
	/** Body text. LIST needs it — hence not Promise<void> (#164/E-19). */
	body: string
}

/**
 * One signed request against an S3-compatible endpoint.
 *
 * Fails closed: any non-2xx throws (S9/ST7). The thrown message carries the status and the
 * provider's body but never a credential — run.ts additionally passes every stored message
 * through sanitizeError.
 */
export async function s3Request(
	target: S3Target,
	method: string,
	path: string,
	query: Record<string, string>,
	body: Buffer | null,
	now: Date = new Date()
): Promise<S3Response> {
	const url = new URL(target.endpoint)
	const payloadHash = sha256Hex(body ?? '')

	// `host` and `content-length` are signed (SigV4 needs host, and AWS's own vectors sign
	// content-length) but they are FORBIDDEN request headers for fetch: undici discards what
	// is passed here and recomputes both from the URL and the body. Verified — a hand-set
	// host never reaches the wire. That is fine ONLY because the signed values are derived
	// from the same two sources undici uses, so the two can never disagree.
	//
	// Keep it that way. If a future change signs a content-length that is not exactly
	// `body.byteLength`, or a host that is not `url.host`, the request will be signed one way
	// and sent another and every call will fail with SignatureDoesNotMatch — silently, because
	// nothing here can observe what undici substituted.
	const headers = signV4(
		{
			method,
			path,
			query,
			headers: {
				host: url.host,
				'x-amz-content-sha256': payloadHash,
				...(body ? { 'content-length': String(body.byteLength) } : {})
			},
			payloadHash
		},
		{ ...target, service: 's3' },
		now
	)

	// Signed with uriEncode, so send the SAME string. URLSearchParams is form-urlencoded and
	// differs on space, `*` and `~` — a continuation token holding one of those would be signed
	// one way and sent another, and the request would fail on a signature mismatch.
	const qs = canonicalQuery(query)
	const res = await fetch(`${url.origin}${path}${qs ? `?${qs}` : ''}`, {
		method,
		headers,
		// Buffer is a Uint8Array at runtime; the DOM lib's BodyInit does not name Buffer.
		body: body ? new Uint8Array(body) : undefined,
		// Undici's default is a 300s *idle* interval, not a total deadline. Without this a
		// stalled S3 call holds the per-org advisory lock for as long as the socket dribbles.
		signal: AbortSignal.timeout(S3_REQUEST_TIMEOUT_MS)
	})
	const text = await res.text()
	if (!res.ok) {
		throw new Error(`S3 ${method} ${path} failed: ${res.status} ${text.slice(0, 200)}`)
	}
	return { status: res.status, body: text }
}
